<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");
$APPLICATION->SetPageProperty("show_sidebar", "N");
?><?$APPLICATION->IncludeComponent(
  "whatasoft:catalog",
  ".default",
  array(
    "IBLOCK_ID" => "3",
    "IBLOCK_TYPE" => "catalog",
    "FORM_IBLOCK_ID" => "20",
    "FORM_IBLOCK_TYPE" => "whatasoft_shop_forms",
    "FORM_CHEAPER_IBLOCK_ID" => "18",
    "FORM_CHEAPER_IBLOCK_TYPE" => "whatasoft_shop_forms",
    "FORM_TITLE" => "Заказ в 1 клик",
    "FORM_CHEAPER_TITLE" => "Нашли дешевле?",
    "ACTION_VARIABLE" => "action",
    "ADD_ELEMENT_CHAIN" => "Y",
    "ADD_SECTIONS_CHAIN" => "Y",
    "AJAX_MODE" => "N",
    "AJAX_OPTION_ADDITIONAL" => "",
    "AJAX_OPTION_HISTORY" => "N",
    "AJAX_OPTION_JUMP" => "N",
    "AJAX_OPTION_STYLE" => "Y",
    "BASKET_URL" => SITE_DIR."cart/",
    "CACHE_FILTER" => "N",
    "CACHE_GROUPS" => "Y",
    "CACHE_TIME" => "36000000",
    "CACHE_TYPE" => "A",
    "COMPOSITE_FRAME_MODE" => "A",
    "COMPOSITE_FRAME_TYPE" => "AUTO",
    "DETAIL_BROWSER_TITLE" => "NAME",
    "DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
    "DETAIL_META_DESCRIPTION" => "-",
    "DETAIL_META_KEYWORDS" => "-",
    "DETAIL_PROPERTY_CODE" => array(
      0 => "DEMO_BRAND",
      1 => "DEMO_WARRANTY",
      2 => "DEMO_COUNTRY",
      3 => "DEMO_TYPE",
      4 => "DEMO_COLOR",
      5 => "DEMO_SIZE",
      6 => "DEMO_POWER",
      7 => "DEMO_MATERIAL",
      8 => "DEMO_AUDIOFORMAT",
      9 => "DEMO_RADIOTUNER",
      10 => "DEMO_CDDISC",
      11 => "DEMO_ROMMEMORY",
      12 => "DEMO_EXTERNALMEMORY",
      13 => "DEMO_NFC",
      14 => "DEMO_BLUETOOTH",
      15 => "DEMO_DISPLAY",
      16 => "DEMO_RECIPESBOOK",
      17 => "DEMO_DELAYEDSTART",
      18 => "DEMO_CORE",
      19 => "DEMO_HDD",
      20 => "DEMO_WEIGHT",
      21 => "DEMO_PLATFORM",
      22 => "DEMO_BITRIX",
    ),
    "DETAIL_SET_CANONICAL_URL" => "N",
    "DETAIL_SHOW_ADDITIONAL_TAB" => "Y",
    "DETAIL_SHOW_ADDITIONAL_TAB_NAME" => "Доставка и оплата",
    "DETAIL_SHOW_TABS" => "Y",
    "DISPLAY_BOTTOM_PAGER" => "Y",
    "DISPLAY_TOP_PAGER" => "N",
    "ELEMENT_SORT_FIELD" => "sort",
    "ELEMENT_SORT_FIELD2" => "id",
    "ELEMENT_SORT_ORDER" => "asc",
    "ELEMENT_SORT_ORDER2" => "desc",
    "FILE_404" => SITE_DIR."404.php",
    "FILTER_NAME" => "",
    "INCLUDE_SUBSECTIONS" => "Y",
    "LIST_BROWSER_TITLE" => "-",
    "LIST_META_DESCRIPTION" => "-",
    "LIST_META_KEYWORDS" => "-",
    "LIST_PROPERTY_CODE" => array(
      0 => "DEMO_COUNTRY",
      1 => "DEMO_TYPE",
      2 => "DEMO_COLOR",
      3 => "DEMO_SIZE",
      4 => "DEMO_POWER",
      5 => "DEMO_MATERIAL",
      6 => "DEMO_AUDIOFORMAT",
      7 => "DEMO_RADIOTUNER",
      8 => "DEMO_CDDISC",
      9 => "DEMO_ROMMEMORY",
      10 => "DEMO_EXTERNALMEMORY",
      11 => "DEMO_NFC",
      12 => "DEMO_BLUETOOTH",
      13 => "DEMO_DISPLAY",
      14 => "DEMO_RECIPESBOOK",
      15 => "DEMO_DELAYEDSTART",
      16 => "DEMO_CORE",
      17 => "DEMO_HDD",
      18 => "DEMO_WEIGHT",
      19 => "DEMO_BITRIX",
      20 => "",
    ),
    "MESSAGE_404" => "",
    "PAGER_BASE_LINK_ENABLE" => "N",
    "PAGER_DESC_NUMBERING" => "N",
    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
    "PAGER_SHOW_ALL" => "N",
    "PAGER_SHOW_ALWAYS" => "N",
    "PAGER_TEMPLATE" => ".default",
    "PAGER_TITLE" => "Товары",
    "PAGE_ELEMENT_COUNT" => "9",
    "PRODUCT_ID_VARIABLE" => "id",
    "SECTION_COUNT_ELEMENTS" => "Y",
    "SECTION_ID_VARIABLE" => "SECTION_ID",
    "SECTION_TOP_DEPTH" => "2",
    "SEF_FOLDER" => "/whatasoft/catalog/",
    "SEF_MODE" => "Y",
    "SET_LAST_MODIFIED" => "N",
    "SET_STATUS_404" => "Y",
    "SET_TITLE" => "Y",
    "SHOW_404" => "Y",
    "SHOW_DEACTIVATED" => "N",
    "USE_ELEMENT_COUNTER" => "Y",
    "USE_FILTER" => "Y",
    "USE_MAIN_ELEMENT_SECTION" => "Y",
    "COMPONENT_TEMPLATE" => ".default",
    "SEF_URL_TEMPLATES" => array(
      "sections" => "",
      "section" => "#SECTION_CODE#/",
      "element" => "#SECTION_CODE#/#ELEMENT_CODE#/",
      "smart_filter" => "#SECTION_CODE#/filter/#SMART_FILTER_PATH#/apply/",
    )
  ),
  false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>