<?$APPLICATION->IncludeComponent(
  "whatasoft:map.yandex.list", 
  ".default", 
  array(
    "IBLOCK_ID" => "11",
    "IBLOCK_TYPE" => "whatasoft_shop_content",
    "BEHAVIORS" => array("DBLCLICK_ZOOM","DRAGGING"),
    "CACHE_FILTER" => "N",
    "CACHE_GROUPS" => "Y",
    "CACHE_TIME" => "36000000",
    "CACHE_TYPE" => "A",
    "CHECK_DATES" => "Y",
    "CONTROLS" => array("TYPE","ZOOM"),
    "DETAIL_URL" => "",
    "FILTER_NAME" => "",
    "INCLUDE_SUBSECTIONS" => "Y",
    "INIT_MAP_TYPE" => "MAP",
    "ITEMS_LIMIT" => "100",
    "MAP_AUTO_SCALE_CENTER" => "Y",
    "MAP_BALLOON_COLOR" => "",
    "MAP_BALLOON_COORDS" => "PROPERTY_COORDS",
    "MAP_BALLOON_DETAIL_IMG" => "FIELD_PREVIEW_PICTURE",
    "MAP_BALLOON_LINK_SHOW" => "N",
    "MAP_BALLOON_NAME" => "FIELD_NAME",
    "MAP_BALLOON_PROPERTIES" => array("ADDRESS","SCHEDULE",""),
    "MAP_BALLOON_TEXT" => "FIELD_PREVIEW_TEXT",
    "MAP_BALLOON_TITLE" => "FIELD_NAME",
    "MAP_CENTER" => "55.752647988985785,37.615171286352556",
    "MAP_CLUSTER" => "Y",
    "MAP_CLUSTER_CONTENT_LEFT_COLUMN_WIDTH" => "120",
    "MAP_CLUSTER_CONTENT_WIDTH" => "400",
    "MAP_CLUSTER_SIMPLE" => "N",
    "MAP_COLOR" => "DB3D3D",
    "MAP_HEIGHT" => "100%",
    "MAP_ICON" => "",
    "MAP_ID" => "",
    "MAP_LIST_SHOW" => "N",
    "MAP_SCALE" => "14",
    "MAP_WIDTH" => "100%",
    "MESSAGE_404" => "",
    "PARENT_SECTION" => "",
    "PARENT_SECTION_CODE" => "",
    "SET_STATUS_404" => "N",
    "SHOW_404" => "N",
    "SORT_BY1" => "SORT",
    "SORT_BY2" => "ID",
    "SORT_ORDER1" => "ASC",
    "SORT_ORDER2" => "DESC",
    "USE_ELEMENT_ICON" => "N",
    "COMPONENT_TEMPLATE" => ".default",
    "COMPOSITE_FRAME_MODE" => "A",
    "COMPOSITE_FRAME_TYPE" => "AUTO",
    "USE_SECTION_ICON" => "N"
  ),
  false
);?>