<?$APPLICATION->IncludeComponent(
  "whatasoft:items.list.simple",
  "news_sidebar",
  Array(
    "BLOCK_TITLE" => "",
    "CACHE_FILTER" => "N",
    "CACHE_GROUPS" => "N",
    "CACHE_TIME" => "36000000",
    "CACHE_TYPE" => "A",
    "CHECK_DATES" => "N",
    "COMPOSITE_FRAME_MODE" => "A",
    "COMPOSITE_FRAME_TYPE" => "AUTO",
    "DETAIL_URL" => "",
    "FILTER_NAME" => "",
    "IBLOCK_ID" => "12",
    "IBLOCK_TYPE" => "whatasoft_shop_content",
    "INCLUDE_SUBSECTIONS" => "Y",
    "ITEMS_COUNT" => "2",
    "MESSAGE_404" => "",
    "PARENT_SECTION" => "",
    "PARENT_SECTION_CODE" => "",
    "PROPERTY_CODE" => array("*",""),
    "SET_STATUS_404" => "N",
    "SHOW_404" => "N",
    "SORT_BY1" => "ACTIVE_FROM",
    "SORT_BY2" => "ID",
    "SORT_ORDER1" => "DESC",
    "SORT_ORDER2" => "DESC"
  )
);?>